/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lenderman_ncidpop_utils_OsUtils */

#ifndef _Included_com_lenderman_ncidpop_utils_OsUtils
#define _Included_com_lenderman_ncidpop_utils_OsUtils
#ifdef __cplusplus
extern "C" {
#endif
    /*
     * Class:     com_lenderman_ncidpop_utils_OsUtils
     * Method:    getMacintoshAddressBookAlias
     * Signature: (Ljava/lang/String;)Ljava/lang/String;
     */
    JNIEXPORT jstring JNICALL Java_com_lenderman_ncidpop_utils_OsUtils_getMacintoshAddressBookAlias
    (JNIEnv *, jclass, jstring);
    
    /*
     * Class:     com_lenderman_ncidpop_utils_OsUtils
     * Method:    getMacintoshAddressBookImage
     * Signature: (Ljava/lang/String;)Ljava/lang/String;
     */
    JNIEXPORT jstring JNICALL Java_com_lenderman_ncidpop_utils_OsUtils_getMacintoshAddressBookImage
    (JNIEnv * env, jclass thisClass, jstring cStringNumber);

    /*
     * Class:     com_lenderman_ncidpop_utils_OsUtils
     * Method:    getMacintoshAddressBookList
     * Signature: ()Ljava/util/HashMap;
     */
    JNIEXPORT jobject JNICALL Java_com_lenderman_ncidpop_utils_OsUtils_getMacintoshAddressBookList
    (JNIEnv *, jclass);
    
    /*
     * Class:     com_lenderman_ncidpop_utils_OsUtils
     * Method:    launchMacintoshAddressBook
     * Signature: (Ljava/lang/String;)V
     */
    JNIEXPORT void JNICALL Java_com_lenderman_ncidpop_utils_OsUtils_launchMacintoshAddressBook
    (JNIEnv *, jclass, jstring);
    
#ifdef __cplusplus
}
#endif
#endif
